package com.jodli.coffeeshottimer.domain.model

/**
 * Domain error codes for Use Cases - following Clean Architecture principles.
 * These should be translated to user-facing strings in the UI layer.
 */
enum class DomainErrorCode(val code: String) {
    // Bean validation errors
    BEAN_ID_EMPTY("BEAN_ID_EMPTY"),
    BEAN_NOT_FOUND("BEAN_NOT_FOUND"),
    BEAN_NAME_EMPTY("BEAN_NAME_EMPTY"),
    BEAN_NAME_EXISTS("BEAN_NAME_EXISTS"),
    GRINDER_SETTING_EMPTY("GRINDER_SETTING_EMPTY"),

    // Operation errors
    FAILED_TO_GET_BEAN("FAILED_TO_GET_BEAN"),
    FAILED_TO_UPDATE_BEAN("FAILED_TO_UPDATE_BEAN"),
    FAILED_TO_ADD_BEAN("FAILED_TO_ADD_BEAN"),
    FAILED_TO_UPDATE_GRINDER_SETTING("FAILED_TO_UPDATE_GRINDER_SETTING"),
    FAILED_TO_UPDATE_ACTIVE_STATUS("FAILED_TO_UPDATE_ACTIVE_STATUS"),
    FAILED_TO_CHECK_BEAN_NAME("FAILED_TO_CHECK_BEAN_NAME"),
    FAILED_TO_GET_ACTIVE_BEANS("FAILED_TO_GET_ACTIVE_BEANS"),
    FAILED_TO_GET_ACTIVE_BEAN_COUNT("FAILED_TO_GET_ACTIVE_BEAN_COUNT"),
    FAILED_TO_CHECK_FOR_ACTIVE_BEANS("FAILED_TO_CHECK_FOR_ACTIVE_BEANS"),

    // Shot validation errors
    SHOT_VALIDATION_FAILED("SHOT_VALIDATION_FAILED"),
    COFFEE_WEIGHT_IN_INVALID("COFFEE_WEIGHT_IN_INVALID"),
    COFFEE_WEIGHT_OUT_INVALID("COFFEE_WEIGHT_OUT_INVALID"),
    EXTRACTION_TIME_INVALID("EXTRACTION_TIME_INVALID"),
    GRINDER_SETTING_INVALID("GRINDER_SETTING_INVALID"),

    // Shot operation errors
    SHOT_NOT_FOUND("SHOT_NOT_FOUND"),
    SHOT_RECORDING_FAILED("SHOT_RECORDING_FAILED"),
    FAILED_TO_RECORD_SHOT("FAILED_TO_RECORD_SHOT"),
    FAILED_TO_GET_SHOT_HISTORY("FAILED_TO_GET_SHOT_HISTORY"),
    FAILED_TO_GET_SHOT_STATISTICS("FAILED_TO_GET_SHOT_STATISTICS"),
    FAILED_TO_DELETE_SHOT("FAILED_TO_DELETE_SHOT"),
    FAILED_TO_GET_SHOT("FAILED_TO_GET_SHOT"),
    ASSOCIATED_BEAN_NOT_FOUND("ASSOCIATED_BEAN_NOT_FOUND"),

    // Grinder adjustment errors
    GRINDER_CONFIG_NOT_FOUND("GRINDER_CONFIG_NOT_FOUND"),
    INVALID_GRIND_SETTING("INVALID_GRIND_SETTING"),
    INVALID_EXTRACTION_TIME("INVALID_EXTRACTION_TIME"),
    CALCULATION_ERROR("CALCULATION_ERROR"),

    // Photo operation errors
    PHOTO_SAVE_FAILED("PHOTO_SAVE_FAILED"),
    PHOTO_DELETE_FAILED("PHOTO_DELETE_FAILED"),
    PHOTO_NOT_FOUND("PHOTO_NOT_FOUND"),
    PHOTO_COMPRESSION_FAILED("PHOTO_COMPRESSION_FAILED"),
    PHOTO_STORAGE_FULL("PHOTO_STORAGE_FULL"),
    PHOTO_INVALID_URI("PHOTO_INVALID_URI"),
    PHOTO_FILE_ACCESS_ERROR("PHOTO_FILE_ACCESS_ERROR"),
    
    // Camera and permission errors
    CAMERA_UNAVAILABLE("CAMERA_UNAVAILABLE"),
    CAMERA_PERMISSION_DENIED("CAMERA_PERMISSION_DENIED"),
    STORAGE_PERMISSION_DENIED("STORAGE_PERMISSION_DENIED"),
    PHOTO_CAPTURE_FAILED("PHOTO_CAPTURE_FAILED"),
    PHOTO_SELECTION_CANCELLED("PHOTO_SELECTION_CANCELLED"),

    // Storage errors
    STORAGE_ERROR("STORAGE_ERROR"),
    
    // Generic errors
    VALIDATION_FAILED("VALIDATION_FAILED"),
    UNKNOWN_ERROR("UNKNOWN_ERROR")
}
