# Detekt configuration for CoffeeShotTimer Android app
# Optimized for AI-generated code patterns and Android development

config:
  validation: true
  warningsAsErrors: false

build:
  maxIssues: 0 # Fail build on any new issues (baseline mode)
  excludeCorrectable: true # Do not fail the build on auto-correctable issues (formatting, simple style)
  weights:
    # Prioritize critical issues for Android apps
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 0

console-reports:
  active: true
  exclude:
    - "ProjectStatisticsReport"
    - "ComplexityReport"
    - "NotificationReport"
    - "FindingsReport"
    - "FileBasedFindingsReport"

output-reports:
  active: true

processors:
  active: true

# Comments - Low priority for AI-generated code
comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  EndOfSentenceFormat:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

# Complexity - High priority for maintainable code
complexity:
  active: true
  excludes: ["**/build.gradle.kts"]
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 20
    includeStaticDeclarations: false
    includePrivateDeclarations: false
  CyclomaticComplexMethod:
    active: true
    threshold: 20 # Higher to accommodate complex UI/Compose logic; revisit in baseline reductions
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
    ignoreNestingFunctions: false
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    threshold: 500 # Slightly permissive for Android; tighten over time
  LongMethod:
    active: true
    threshold: 120 # Allow larger @Composable and UI methods; revisit over time
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 9 # Slightly higher for Android constructors
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotated: ["Composable"]
  MethodOverloading:
    active: false
  NestedBlockDepth:
    active: true
    threshold: 4
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

# Coroutines - Critical for Android async operations
coroutines:
  active: true
  InjectDispatcher:
    active: true
    dispatcherNames:
      - "IO"
      - "Default"
      - "Unconfined"
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

# Empty blocks - Important for identifying incomplete AI-generated code
empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

# Exceptions - Critical for Android app stability
exceptions:
  active: true
  excludes: ["**/test/**", "**/androidTest/**"]
  ExceptionRaisedInUnexpectedLocation:
    active: false
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - Error
      - Exception
      - Throwable
      - RuntimeException

# Naming - Important for Android conventions
naming:
  active: true
  ClassNaming:
    active: true
    classPattern: "[A-Z][a-zA-Z0-9]*"
  ConstructorParameterNaming:
    active: true
    parameterPattern: "[a-z][A-Za-z0-9]*"
    privateParameterPattern: "[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"
  EnumNaming:
    active: true
    enumEntryPattern: "[A-Z][_a-zA-Z0-9]*"
  ForbiddenClassName:
    active: false
  FunctionMaxLength:
    active: false
  FunctionMinLength:
    active: false
  FunctionNaming:
    active: true
    functionPattern: "([a-z][a-zA-Z0-9]*)|(`.*`)"
    excludeClassPattern: "$^"
    ignoreAnnotated: ["Composable"] # Allow different naming for Compose functions
  FunctionParameterNaming:
    active: true
    parameterPattern: "[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"
  InvalidPackageDeclaration:
    active: false
  MatchingDeclarationName:
    active: true
    mustBeFirst: true
  MemberNameEqualsClassName:
    active: true
    ignoreOverridden: true
  ObjectPropertyNaming:
    active: true
    constantPattern: "[A-Za-z][_A-Za-z0-9]*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "(_)?[A-Za-z][_A-Za-z0-9]*"
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: "[A-Z][_A-Z0-9]*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "_?[A-Za-z][_A-Za-z0-9]*"
  VariableMaxLength:
    active: false
  VariableMinLength:
    active: false
  VariableNaming:
    active: true
    variablePattern: "[a-z][A-Za-z0-9]*"
    privateVariablePattern: "(_)?[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"

# Performance - Critical for mobile apps
performance:
  active: true
  ArrayPrimitive:
    active: false
  ForEachOnRange:
    active: true
    excludes: ["**/test/**", "**/androidTest/**"]
  SpreadOperator:
    active: true
    excludes: ["**/test/**", "**/androidTest/**"]
  UnnecessaryTemporaryInstantiation:
    active: true

# Potential bugs - Highest priority
potential-bugs:
  active: true
  excludes: ["**/test/**", "**/androidTest/**"]
  Deprecation:
    active: false
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false
  IgnoredReturnValue:
    active: true
    severity: error
  ImplicitDefaultLocale:
    active: false
  ImplicitUnitReturnType:
    active: false
  InvalidRange:
    active: false
  IteratorHasNextCallsNextMethod:
    active: false
  IteratorNotThrowingNoSuchElementException:
    active: false
  LateinitUsage:
    active: false
  MapGetWithNotNullAssertionOperator:
    active: false
  UnconditionalJumpStatementInLoop:
    active: false
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
    severity: error
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: false
  WrongEqualsTypeParameter:
    active: true

# Style - Medium priority, focused on consistency
style:
  excludes: ["**/build.gradle.kts"]
  active: true
  CollapsibleIfStatements:
    active: false
  DataClassShouldBeImmutable:
    active: false
  EqualsNullCall:
    active: false
  EqualsOnSignatureLine:
    active: false
  ExplicitCollectionElementAccessMethod:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: true
    comments: ["TODO:", "FIXME:", "STOPSHIP:", "HACK:", "XXX:"]
    allowedPatterns: ""
  ForbiddenImport:
    active: false
  ForbiddenMethodCall:
    active: false
  ForbiddenVoid:
    active: false
  FunctionOnlyReturningConstant:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: true
    excludes: ["**/test/**", "**/androidTest/**"]
    ignoreNumbers: ["-1", "0", "1", "2"]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
  MaxLineLength:
    active: false
    maxLineLength: 120 # Enforced by formatting.MaximumLineLength
    excludes: ["**/build.gradle.kts", "**/test/**", "**/androidTest/**"]
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  MayBeConst:
    active: false
  ModifierOrder:
    active: true
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfFile:
    active: true
  NoTabs:
    active: false
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  RedundantExplicitType:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  ReturnCount:
    active: true
    max: 2
    excludedFunctions: ["equals"]
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: false
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: false
  ThrowsCount:
    active: true
    max: 2
  TrailingWhitespace:
    active: false
  UnderscoresInNumericLiterals:
    active: false
  UnnecessaryAbstractClass:
    active: false
  UnnecessaryAnnotationUseSiteTarget:
    active: false
  UnnecessaryApply:
    active: false
  UnnecessaryInheritance:
    active: false
  UnnecessaryLet:
    active: false
  UnnecessaryParentheses:
    active: false
  UntilInsteadOfRangeTo:
    active: false
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: false
  UnusedPrivateProperty:
    active: false
  UnusedPrivateMember:
    active: true
  UseArrayLiteralsInAnnotations:
    active: false
  UseCheckOrError:
    active: false
  UseDataClass:
    active: false
  UseEmptyCounterpart:
    active: false
  UseIfEmptyOrIfBlank:
    active: false
  UseIfInsteadOfWhen:
    active: false
  UseIsNullOrEmpty:
    active: false
  UseOrEmpty:
    active: false
  UseRequire:
    active: false
  UseRequireNotNull:
    active: false
  UselessCallOnNotNull:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  VarCouldBeVal:
    active: false
  WildcardImport:
    active: true
    excludes: ["**/test/**", "**/androidTest/**"]
    excludeImports: ["java.util.*", "kotlinx.android.synthetic.*"]

formatting:
  active: true
  android: true
  AutoCorrect: true
  MaximumLineLength:
    active: true
    maxLineLength: 120
# Custom rule sets can be added here for specific espresso timer patterns
